### PR TITLE
 Support OpenHarmony

### PR DESCRIPTION
**Pull request by zmtzawqlp**
To avoid affecting the adaptation version of the main project, I've separated all implementations into vibration_platform_interface. This allows the implementation for the Ohos platform to be done without impacting the main project.

### CODE REVIEW

**Comment by benjamindean** [comment]
Thanks for the contribution! I'll have to manually test it, so it'll take some time.

**Comment by zmtzawqlp** [comment]
After all  check are completed, please publish vibration_platform_interface and vibration to pub.dev. If possible, let me publish vibration_ohos to pub.dev, because the OpenHarmony API is still unstable and requires frequent updates. Thank you.

**Comment by benjamindean** [comment]
Sure! You can publish it on your own. I'll try to publish platform interface by the end of the week.

**Review by benjamindean — APPROVED** [review]

**Comment by zmtzawqlp** [comment]
@benjamindean do you have publish   vibration_platform_interface into to pub.dev?

**Comment by benjamindean** [comment]
All done! You can publish `vibration_ohos` now.

**Comment by benjamindean** [comment]
@zmtzawqlp Hey! I updated the platform interface package and, most likely, you have to publish a new version of OHOS plugin. It's already on master branch here.

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp Hey! I updated the platform interface package and, most likely, you have to publish a new version of OHOS plugin. It's already on master branch here.

ok， i will update it assp

**Comment by zmtzawqlp** [comment]
@benjamindean please check this pr if you have a time.  https://github.com/benjamindean/flutter_vibration/pull/122

**Pull request merged**
