### PR TITLE
Made some modifications on the IOS implementation to unify behavior with Android’s one.

### PR DESCRIPTION
**Pull request by Leicas**
Only thing not working now on iOS is the vibration without Amplitude (only pattern). I unfortunately don’t have access to iOS hardware anymore so cannot implement that.

Amplitudes is confirmed to work and the test app works similarly on iOS and Android.

### CODE REVIEW

**Comment by benjamindean** [comment]
Thank you for the contribution! Could you, please, format the code so it's easier to see the diff?

**Comment by Leicas** [comment]
Yes, sorry about that was just happy I got it to work and forgot to clean the code!

**Comment by benjamindean** [comment]
Thanks! I will try to test it as soon as I can.

**Comment by furkankurt** [comment]
Any update?

**Comment by Skyost** [comment]
Hey @benjamindean !

Just saw that you've been worked on this project recently 😁    
Did you have time to review this PR ?

**Comment by benjamindean** [comment]
Hey! Yeah, I guess I cn safely merge it now. Thanks for notifying!

**Comment by benjamindean** [comment]
Will release a new version as soon as the web implementation is fixed.

**Pull request merged**
